In [81]:
import pandas as pd
import numpy as np
url='https://raw.githubusercontent.com/shankygupta79/GoogleCollabFiles/master/House%20Prediction/Train_DataX.csv'
url2='https://raw.githubusercontent.com/shankygupta79/GoogleCollabFiles/master/House%20Prediction/Train_DataY.csv'
dft= pd.read_csv('Test_Data.csv')
df = pd.read_csv(url)
xt=df.values
yt=pd.read_csv(url2).values
print(xt.shape)
columns_to_drop = ["Id","Street","Alley","LotShape","LandContour","Utilities","LandSlope","RoofMatl","YearBuilt","YearRemodAdd","Exterior2nd","MasVnrType","Exterior1st","BsmtFinSF1","BsmtUnfSF","BsmtFinSF2","BsmtFinType2","BsmtFinType1"]
yt=yt.reshape(-1)
print (yt.shape)
col=df.columns.values

(1100, 80)
(1100,)

In [85]:
from sklearn.preprocessing import LabelEncoder
#df = df.drop(columns_to_drop,axis=1)
#dft = dft.drop(columns_to_drop,axis=1)
le = LabelEncoder()
col=list(df.columns)
a=list(df.dtypes)
import matplotlib.pyplot as plt

count=0
features=[]
for i in range(0,df.values.shape[1],1):
    if(a[i]=='object'):
        df[col[i]].fillna('NaN',inplace=True)
        dft[col[i]].fillna('NaN',inplace=True)
        df[col[i]] = le.fit_transform(df[col[i]])
        dft[col[i]] = le.fit_transform(dft[col[i]])
    else:
        df[col[i]].fillna(0,inplace=True)
        dft[col[i]].fillna(0,inplace=True)
    sx=df.values[:,i]
    
    reg = LinearRegression().fit(sx.reshape(-1,1), yt)
    lis = np.arange(min(sx),max(sx),0.5)
    if(reg.coef_>0):
        
        pred=reg.predict(lis.reshape(-1,1))
        if(reg.score(sx.reshape(-1,1),yt)>0.2):
            print()
            #plt.scatter(sx,yt)
            #plt.scatter(lis,pred)
            #plt.title(col[i])
            #plt.show()
        else:
            features.append(col[i])
    else:
        features.append(col[i])
features=np.array(features)           
print(features.shape)

(16,)

In [86]:
df = df.drop(features,axis=1)
dft = dft.drop(features,axis=1)
dft.head(n=10)

,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea
0,2,1920,1950,0.0,290,438,438,1,3,0,1,246
1,5,1971,1971,0.0,950,950,950,1,5,0,1,280
2,5,1960,2002,45.0,1010,1134,1134,1,6,0,1,254
3,6,1959,1959,0.0,655,1194,1194,1,6,1,2,539
4,5,1970,1970,304.0,630,630,1302,2,6,0,2,440
5,8,1994,1995,362.0,1463,1500,2622,2,9,2,2,712
6,7,1990,1991,0.0,910,1442,1442,2,6,1,2,719
7,7,2006,2006,0.0,868,887,2021,2,9,1,2,422
8,6,2000,2000,0.0,924,948,1690,2,7,1,2,463
9,8,2004,2005,42.0,1836,1836,1836,2,7,1,3,862

In [87]:
xt=df.values
import numpy as np
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(xt, yt)
print(reg.score(xt, yt))
pred1=reg.predict(dft.values)
dfp=pd.DataFrame(pred1)
dfp.columns = ['SalePrice']
dfp.to_csv('Aannnns2.csv')

0.8121853866601827